/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;



import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenfu
 */
public class buyproduct extends javax.swing.JFrame {
        
    private static int total = 0; 
    private static int transactionno=0; 
    private static int customerno = 0;
    
    /**
     * Creates new form
     */
    public buyproduct() {
        super("Buy Product"); 
        initComponents();
        customerno++; 
        customeroutput.setText(" "+customerno);
        transactionno++; 
        transactionoutput.setText(" "+transactionno);
        
    }
    
    public int getTotal(){
        return total; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        finaltotal = new javax.swing.JTextField();
        totallbl = new javax.swing.JLabel();
        productcodelbl = new javax.swing.JLabel();
        productcodeinput = new javax.swing.JTextField();
        descriptionlbl = new javax.swing.JLabel();
        descriptioninput = new javax.swing.JTextField();
        qtylbl = new javax.swing.JLabel();
        qtyinput = new javax.swing.JTextField();
        pricelbl = new javax.swing.JLabel();
        priceinput = new javax.swing.JTextField();
        transactionnolbl = new javax.swing.JLabel();
        transactionoutput = new javax.swing.JTextField();
        customeroutput = new javax.swing.JTextField();
        customernumberlbl = new javax.swing.JLabel();
        buy = new javax.swing.JButton();
        paymentinput = new javax.swing.JTextField();
        paymentlbl = new javax.swing.JLabel();
        changelbl = new javax.swing.JLabel();
        changeoutput = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productcode", "Description", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(data);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        finaltotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finaltotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        getContentPane().add(finaltotal, gridBagConstraints);

        totallbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        totallbl.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 22, 0, 0);
        getContentPane().add(totallbl, gridBagConstraints);

        productcodelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        productcodelbl.setText("Product Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 23, 0, 0);
        getContentPane().add(productcodelbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 23, 0, 0);
        getContentPane().add(productcodeinput, gridBagConstraints);

        descriptionlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        descriptionlbl.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 23, 0, 0);
        getContentPane().add(descriptionlbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(descriptioninput, gridBagConstraints);

        qtylbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        qtylbl.setText("Qty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 23, 0, 0);
        getContentPane().add(qtylbl, gridBagConstraints);

        qtyinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyinputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(qtyinput, gridBagConstraints);

        pricelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pricelbl.setText("Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 23, 0, 0);
        getContentPane().add(pricelbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(priceinput, gridBagConstraints);

        transactionnolbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        transactionnolbl.setText("Transaction no.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 28, 0, 0);
        getContentPane().add(transactionnolbl, gridBagConstraints);

        transactionoutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionoutputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 28, 0, 0);
        getContentPane().add(transactionoutput, gridBagConstraints);

        customeroutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeroutputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 28, 0, 0);
        getContentPane().add(customeroutput, gridBagConstraints);

        customernumberlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customernumberlbl.setText("Customer number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 28, 0, 0);
        getContentPane().add(customernumberlbl, gridBagConstraints);

        buy.setBackground(new java.awt.Color(51, 204, 0));
        buy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buy.setText("Buy");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 15, 0, 0);
        getContentPane().add(buy, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(paymentinput, gridBagConstraints);

        paymentlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        paymentlbl.setText("Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 26, 0, 0);
        getContentPane().add(paymentlbl, gridBagConstraints);

        changelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        changelbl.setText("Change ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 22, 0, 0);
        getContentPane().add(changelbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 0);
        getContentPane().add(changeoutput, gridBagConstraints);

        pay.setBackground(new java.awt.Color(102, 255, 102));
        pay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 13, 0);
        getContentPane().add(pay, gridBagConstraints);

        reset.setBackground(new java.awt.Color(255, 51, 51));
        reset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 54, 0, 0);
        getContentPane().add(reset, gridBagConstraints);

        back.setBackground(new java.awt.Color(255, 255, 102));
        back.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 23, 0, 0);
        getContentPane().add(back, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finaltotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finaltotalActionPerformed
        // TODO add your handling code here:
        finaltotal.setText("Php: "+getTotal());
    }//GEN-LAST:event_finaltotalActionPerformed

    private void qtyinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyinputActionPerformed

    private void transactionoutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionoutputActionPerformed
        // TODO add your handling code here:
        transactionno++; 
        transactionoutput.setText(" "+transactionno);
    }//GEN-LAST:event_transactionoutputActionPerformed

    private void customeroutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeroutputActionPerformed
        // TODO add your handling code here:
        customerno++; 
        customeroutput.setText(" "+customerno);
    }//GEN-LAST:event_customeroutputActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        //user can input the details and place it to the table and it can also compute the final total
        String productcode = productcodeinput.getText(); 
        String description = descriptioninput.getText(); 
        String qty = qtyinput.getText(); 
        int qtyint = Integer.parseInt(qty); 
        String price = priceinput.getText(); 
        int priceint = Integer.parseInt(price); 
        String dataadd [] = {productcode, description, qty, price};
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        tblmodel.addRow(dataadd);
        int sum = qtyint*priceint; 
        total+=sum; 
        finaltotal.setText("Php: "+getTotal());
        
    }//GEN-LAST:event_buyActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        // program will compute the payment and the change afterwards
        String payment = paymentinput.getText(); 
        int paymentint = Integer.parseInt(payment); 
        int sum = paymentint - total;
        changeoutput.setText("Php: "+sum);
         
         
        
    }//GEN-LAST:event_payActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        // if change has been given, user can reset the entire application
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        tblmodel.setRowCount(0);
        // setting all jtextfields to blank
        productcodeinput.setText("");
        descriptioninput.setText("");
        qtyinput.setText("");
        priceinput.setText("");
        finaltotal.setText("");
        paymentinput.setText(""); 
        changeoutput.setText("");
        transactionno++; 
        transactionoutput.setText(""+transactionno); 
        customerno++; 
        customeroutput.setText(" "+customerno);
        
        
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //program under the buy product form will close
        setVisible(false); 
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton buy;
    private javax.swing.JLabel changelbl;
    private javax.swing.JTextField changeoutput;
    private javax.swing.JLabel customernumberlbl;
    private javax.swing.JTextField customeroutput;
    private javax.swing.JTable data;
    private javax.swing.JTextField descriptioninput;
    private javax.swing.JLabel descriptionlbl;
    private javax.swing.JTextField finaltotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pay;
    private javax.swing.JTextField paymentinput;
    private javax.swing.JLabel paymentlbl;
    private javax.swing.JTextField priceinput;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JTextField productcodeinput;
    private javax.swing.JLabel productcodelbl;
    private javax.swing.JTextField qtyinput;
    private javax.swing.JLabel qtylbl;
    private javax.swing.JButton reset;
    private javax.swing.JLabel totallbl;
    private javax.swing.JLabel transactionnolbl;
    private javax.swing.JTextField transactionoutput;
    // End of variables declaration//GEN-END:variables

    private String toString(int transactionno) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
