/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenfu
 */


public class datainventory extends javax.swing.JFrame {
    /**
     * Creates new form datainventory
     */
    
    private ArrayList<product>productlist; 
    
    public datainventory() {
        super("Data Inventory");
        initComponents();
        productlist = new ArrayList<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        productcodeinput = new javax.swing.JTextField();
        productcodelbl = new javax.swing.JLabel();
        descriptionlbl = new javax.swing.JLabel();
        descriptioninput = new javax.swing.JTextField();
        qtylbl = new javax.swing.JLabel();
        qtyinput = new javax.swing.JTextField();
        pricelbl = new javax.swing.JLabel();
        priceinput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        buyproductbutton = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add.setBackground(new java.awt.Color(102, 255, 102));
        add.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(102, 102, 255));
        update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        productcodeinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productcodeinputActionPerformed(evt);
            }
        });

        productcodelbl.setBackground(new java.awt.Color(153, 255, 153));
        productcodelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        productcodelbl.setText("Product Code");

        descriptionlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        descriptionlbl.setText("Description");

        qtylbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        qtylbl.setText("QTY");

        qtyinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyinputActionPerformed(evt);
            }
        });

        pricelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pricelbl.setText("Price");

        priceinput.setToolTipText("");

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Description", "QTY", "Price"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        buyproductbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buyproductbutton.setText("Buy Product");
        buyproductbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyproductbuttonActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(153, 153, 255));
        logout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pricelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(201, 201, 201))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(qtylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(205, 205, 205))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descriptionlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(167, 167, 167))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productcodelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(priceinput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtyinput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptioninput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productcodeinput, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(buyproductbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(162, 162, 162)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productcodelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productcodeinput)
                .addGap(18, 18, 18)
                .addComponent(descriptionlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(descriptioninput)
                .addGap(26, 26, 26)
                .addComponent(qtylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtyinput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(priceinput)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(buyproductbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productcodeinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productcodeinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productcodeinputActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String productcode = productcodeinput.getText(); 
        String description = descriptioninput.getText(); 
       
        String qty = qtyinput.getText(); 
        int qtyint = Integer.parseInt(qtyinput.getText());
        String price = priceinput.getText(); 
        int priceint = Integer.parseInt(priceinput.getText());
        // data will be filled and transfered via table 
        String dataadd [] = {productcode, description, qty, price};
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        tblmodel.addRow(dataadd);
        product Product = new product(productcode, description, qtyint, priceint); 
        productlist.add(Product);
        JOptionPane.showMessageDialog(null, "Product Recorded Successfully");
        productcodeinput.setText("");
        descriptioninput.setText("");
        qtyinput.setText("");
        priceinput.setText("");
    }//GEN-LAST:event_addActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        String tblproductcode = tblmodel.getValueAt(data.getSelectedRow(), 0).toString();
        String tbldescription = tblmodel.getValueAt(data.getSelectedRow(), 1).toString();
        String tblqty = tblmodel.getValueAt(data.getSelectedRow(), 2).toString();
        String tblprice = tblmodel.getValueAt(data.getSelectedRow(), 3).toString();
        int tblqtyint = Integer.parseInt(tblqty); 
        int tblpriceint = Integer.parseInt(tblprice);
        
        product Product = new product(tblproductcode, tbldescription, tblqtyint, tblpriceint); 
        productlist.add(Product); 
        productcodeinput.setText(tblproductcode);
        descriptioninput.setText(tbldescription);
        qtyinput.setText(tblqty);
        priceinput.setText(tblprice);
        
    }//GEN-LAST:event_dataMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        if(data.getSelectedRowCount() == 1){
            //deletes the row
            tblmodel.removeRow(data.getSelectedRowCount());
        }
        else{
            if(data.getSelectedRowCount() == 0 ){
                JOptionPane.showMessageDialog(null, "Table is empty"); 
            }
            else{
                JOptionPane.showMessageDialog(null, "Please click a selected row first"); 
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)data.getModel(); 
        if(data.getSelectedRowCount() == 1){
            String updateproductcode = productcodeinput.getText(); 
            String updatedescription = descriptioninput.getText();
            String updateqty = qtyinput.getText(); 
            String updateprice = priceinput.getText(); 
            //updates the row of the inputted rows
            tblmodel.setValueAt(updateproductcode, data.getSelectedRow(), 0);
             tblmodel.setValueAt(updatedescription, data.getSelectedRow(), 1);
              tblmodel.setValueAt(updateqty, data.getSelectedRow(), 2);
               tblmodel.setValueAt(updateprice, data.getSelectedRow(), 3);
               //update display
              JOptionPane.showMessageDialog(null, "Update Successful");
        }
        else{//if table is empty
            if(data.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Table is empty");
            }else{
                //if jtextfield is empty
                JOptionPane.showMessageDialog(null, "Please enter the textfields first");
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void buyproductbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyproductbuttonActionPerformed
        // TODO add your handling code here:
        //directs to the buyproduct.java file without closing the datainventory form
        buyproduct bp = new buyproduct(); 
        bp.setVisible(true);
        
    }//GEN-LAST:event_buyproductbuttonActionPerformed

    private void qtyinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyinputActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        // object or method call to go back to login.java
       ArrayList<String>idnumlist = new ArrayList<>(); 
       ArrayList<String>namelist = new ArrayList<>(); 
      ArrayList<String>passwordlist = new ArrayList<>();   
        login lg = new login(idnumlist, namelist, passwordlist); 
        lg.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datainventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datainventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datainventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datainventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datainventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton buyproductbutton;
    private javax.swing.JTable data;
    private javax.swing.JButton delete;
    private javax.swing.JTextField descriptioninput;
    private javax.swing.JLabel descriptionlbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField priceinput;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JTextField productcodeinput;
    private javax.swing.JLabel productcodelbl;
    private javax.swing.JTextField qtyinput;
    private javax.swing.JLabel qtylbl;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
