/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kenfu
 */
public class login extends javax.swing.JFrame {
     private ArrayList<String>idnumlist; 
      private ArrayList<String>namelist; 
      private ArrayList<String>passwordlist; 
    /**
     * Creates new form login
     * @param idnumlist
     * @param namelist
     * @param passwordlist
     */
    public login(ArrayList <String> idnumlist, ArrayList<String> namelist, ArrayList<String> passwordlist) {
        super("Login"); 
        this.idnumlist = idnumlist; 
        this.namelist = namelist; 
        this.passwordlist = passwordlist; 
        initComponents();
       
      }
    
    public void setidnumlist(ArrayList<String>idnumlist){
        this.idnumlist = idnumlist;
    }
    
     public void setnamelist(ArrayList<String>namelist){
        this.namelist = namelist; 
    }
  
      public void setpasswordlist(ArrayList<String>passwordlist){
        this.passwordlist = passwordlist;
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        idnumberinput = new javax.swing.JTextField();
        idnumberlbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        passwordinput = new javax.swing.JPasswordField();
        idnuminput = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        nameinput = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        idnumberlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        idnumberlbl.setText("IDNUMBER");
        idnumberlbl.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 55, 0, 0);
        getContentPane().add(idnumberlbl, gridBagConstraints);

        passwordlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passwordlbl.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 55, 0, 0);
        getContentPane().add(passwordlbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 133, 0, 103);
        getContentPane().add(passwordinput, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 133, 0, 103);
        getContentPane().add(idnuminput, gridBagConstraints);

        login.setBackground(new java.awt.Color(51, 255, 51));
        login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 148, 39, 0);
        getContentPane().add(login, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 133, 0, 103);
        getContentPane().add(nameinput, gridBagConstraints);

        namelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        namelbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 55, 0, 0);
        getContentPane().add(namelbl, gridBagConstraints);

        signup.setBackground(new java.awt.Color(102, 102, 255));
        signup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 81, 39, 0);
        getContentPane().add(signup, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try{
        String idnumber = idnuminput.getText();
        
        String name = nameinput.getText(); 
        String password = String.valueOf(passwordinput.getPassword());
        //program will search in the arraylist data if the data is found and matches the inputted fields.
        if(idnumlist.contains(idnumber)&&namelist.contains(name)&&passwordlist.get(idnumlist.indexOf(idnumber)).equals(password)){
            JOptionPane.showMessageDialog(null, "Login Successful");
            datainventory di  = new datainventory(); 
            di.setVisible(true);
            setVisible(false); 
        }
        else{//if the fields does not match
            JOptionPane.showMessageDialog(null, "Login Failed"); 
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:\
        //program will direct to signup if the user has not got an account yet
        signup su = new signup(); 
        su.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       signup Signup = new signup(); 
       ArrayList <String> idnumlist = Signup.getIdnumlist();
       ArrayList<String> namelist = Signup.getNameList(); 
       ArrayList<String> passwordlist = Signup.getpasswordlist();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login(idnumlist, namelist, passwordlist).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idnumberinput;
    private javax.swing.JLabel idnumberlbl;
    private javax.swing.JTextField idnuminput;
    private javax.swing.JButton login;
    private javax.swing.JTextField nameinput;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPasswordField passwordinput;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
