/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kenfu
 */
public class signup extends javax.swing.JFrame {
    //this will store all the contents and details of the user under the signup  form
       private ArrayList<String>idnumlist = new ArrayList<>();
        private ArrayList<String>namelist = new ArrayList<>();
         private ArrayList<String>passwordlist = new ArrayList<>();
         
         public ArrayList<String>getIdnumlist(){
             return idnumlist; 
         }
         
         public ArrayList<String>getNameList(){
             return namelist; 
         }
         
         public ArrayList<String>getpasswordlist(){
             return passwordlist;
         }
    /**
     * Creates new form signup
     */
    public signup() {
        super("Signup"); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        idnumberlbl = new javax.swing.JLabel();
        idnumberinput = new javax.swing.JTextField();
        nameinput = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        passwordinput = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        confirmpasswordlbl = new javax.swing.JLabel();
        confirmpasswordinput = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        idnumberlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        idnumberlbl.setText("IDNUMBER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 55, 0, 0);
        getContentPane().add(idnumberlbl, gridBagConstraints);

        idnumberinput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 175, 0, 103);
        getContentPane().add(idnumberinput, gridBagConstraints);

        nameinput.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameinputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 175, 0, 103);
        getContentPane().add(nameinput, gridBagConstraints);

        namelbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        namelbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 55, 0, 0);
        getContentPane().add(namelbl, gridBagConstraints);

        passwordlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passwordlbl.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 55, 0, 0);
        getContentPane().add(passwordlbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 175, 0, 103);
        getContentPane().add(passwordinput, gridBagConstraints);

        signup.setBackground(new java.awt.Color(102, 102, 255));
        signup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 223, 53, 0);
        getContentPane().add(signup, gridBagConstraints);

        confirmpasswordlbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        confirmpasswordlbl.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 55, 0, 0);
        getContentPane().add(confirmpasswordlbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 175, 0, 103);
        getContentPane().add(confirmpasswordinput, gridBagConstraints);

        login.setBackground(new java.awt.Color(51, 255, 51));
        login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 53, 0);
        getContentPane().add(login, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        //getting text from fields 
        String idnumber =idnumberinput.getText(); 
        String name = nameinput.getText(); 
        String password = String.valueOf(passwordinput.getPassword());
        String confirmpassword = String.valueOf(confirmpasswordinput.getPassword()); 
        
        try{
            // if the textfields are empty
        if(name.isEmpty()||password.isEmpty()|| idnumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input the fields first");
        }
        else if(idnumlist.contains(idnumber)){// if the ifdnumber exists
         JOptionPane.showMessageDialog(null, "Account already exists");
         idnumberinput.setText("");
        nameinput.setText("");
        passwordinput.setText("");
        confirmpasswordinput.setText("");
        }else if(!password.equals(confirmpassword)){// if the password and the confirm password does not match
            JOptionPane.showMessageDialog(null, "Password not matched");
         passwordinput.setText("");
        confirmpasswordinput.setText("");
        }else{// if ok, account will be recored via arraylist
             JOptionPane.showMessageDialog(null, "Account Recorded Successfully");
        idnumlist.add(idnumber); 
        namelist.add(name); 
        passwordlist.add(password); 
        login lg = new login(idnumlist, namelist, passwordlist);
        lg.setidnumlist(idnumlist);
        lg.setnamelist(namelist);
        lg.setpasswordlist(passwordlist);
        idnumberinput.setText("");
        nameinput.setText("");
        passwordinput.setText("");
        confirmpasswordinput.setText("");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        // if user has an account already and if he presses the login button, the program will direct the 
        // user to the login form
        login lg = new login(idnumlist, namelist, passwordlist); 
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_loginActionPerformed

    private void nameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameinputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpasswordinput;
    private javax.swing.JLabel confirmpasswordlbl;
    private javax.swing.JTextField idnumberinput;
    private javax.swing.JLabel idnumberlbl;
    private javax.swing.JButton login;
    private javax.swing.JTextField nameinput;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPasswordField passwordinput;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
