/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalActivityno;

import javax.swing.JOptionPane;

/**
 *
 * @author kenfu
 */
public class FinalActivityno1_FutamataKento extends javax.swing.JFrame {
    private static int points  = 0; 
    
    
    /**
     * @param points
     */
    public FinalActivityno1_FutamataKento() {
        initComponents();
       
    }
     public FinalActivityno1_FutamataKento(int points) {
        this.points = points; 
       
    }
    public int getPoints1(){
        return points; 
    }
    
    public int computation(){
        FinalActivityno1_FutamataKento2 FA_2 = new FinalActivityno1_FutamataKento2(); 
        FinalActivityno1_FutamataKento3 FA_3 = new FinalActivityno1_FutamataKento3(); 
        FinalActivityno1_FutamataKento4 FA_4 = new FinalActivityno1_FutamataKento4(); 
        FinalActivityno1_FutamataKento5 FA_5 = new FinalActivityno1_FutamataKento5(); 
        int point1 = getPoints1();
        int point2 = FA_2.getpoints2(); 
        int point3 = FA_3.getpoints3(); 
        int point4 = FA_4.getpoints4(); 
        int point5 = FA_5.getpoints5();
        int sum = point1+point2+point3+point4+point5; 
        return sum;
    }
    public void displaypoint(){
        JOptionPane.showMessageDialog(null, "You score: "+computation()+"Proceed"); 
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LetterA = new javax.swing.JCheckBox();
        LetterB = new javax.swing.JCheckBox();
        LetterC = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LetterA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LetterA.setText("A. C++");

        LetterB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LetterB.setText("B. Java");

        LetterC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LetterC.setText("C. high-level language");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("1. The most basic circuitry-level computer language is .");

        submitbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LetterA)
                            .addComponent(LetterB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LetterC)
                                .addGap(153, 153, 153)
                                .addComponent(submitbutton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LetterA)
                        .addGap(18, 18, 18)
                        .addComponent(LetterB)
                        .addGap(18, 18, 18)
                        .addComponent(LetterC))
                    .addComponent(submitbutton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource(); 
       
         
          if(LetterA.isSelected() && LetterB.isSelected() && LetterC.isSelected()){
            points+=1;
          
            JOptionPane.showMessageDialog(null, "You score 1 point"); 
                FinalActivityno1_FutamataKento FA1_1 = new FinalActivityno1_FutamataKento(points);
                FA1_1.displaypoint();
             FinalActivityno1_FutamataKento2 FA1_2 = new FinalActivityno1_FutamataKento2 (); 
             FA1_2.setVisible(true);
             setVisible(false); 
        }
          else if (LetterA.isSelected() && LetterB.isSelected()||LetterA.isSelected()&&LetterC.isSelected()){
             points+=2;
             JOptionPane.showMessageDialog(null, "You score 2 points");
             FinalActivityno1_FutamataKento FA1_1 = new FinalActivityno1_FutamataKento(points);
                FA1_1.displaypoint();
             FinalActivityno1_FutamataKento2 FA1_2 = new FinalActivityno1_FutamataKento2 (); 
             FA1_2.setVisible(true);
             setVisible(false); 
         }
        
          else if(LetterA.isSelected()){
             points+=5; 
             JOptionPane.showMessageDialog(null, "You score 5 points"); 
                FinalActivityno1_FutamataKento FA1_1 = new FinalActivityno1_FutamataKento(points);
                FA1_1.displaypoint();
             FinalActivityno1_FutamataKento2 FA1_2= new FinalActivityno1_FutamataKento2 (); 
             FA1_2.setVisible(true);
             setVisible(false); 
         }
          else if(LetterB.isSelected()||LetterC.isSelected()||LetterB.isSelected()&&LetterC.isSelected()){ 
              JOptionPane.showMessageDialog(null, "Wrong Answer!");
          }
        
         
         
        
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalActivityno1_FutamataKento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalActivityno1_FutamataKento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalActivityno1_FutamataKento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalActivityno1_FutamataKento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalActivityno1_FutamataKento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox LetterA;
    private javax.swing.JCheckBox LetterB;
    private javax.swing.JCheckBox LetterC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
